# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "Install jekyll"
    init: |
      ruby -v
      gem -v
      gcc -v
      g++ -v
      make -v
      gem install jekyll bundler
      bundle install
    command: jekyll serve

vscode:
  extensions:
    - github.copilot
    - michelemelluso.gitignore
    - foxundermoon.shell-format
    - timonwong.shellcheck
    - hexcodetechnologies.vscode-prettydiff
    - neilding.language-liquid

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
