# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "Install jekyll"
    init: |
      ruby -v
      gem -v
      gcc -v
      g++ -v
      make -v
      gem install jekyll bundler
      bundle install
    command: jekyll serve

vscode:
  extensions:
    - ms-ceintl.vscode-language-pack-zh-hans
    - github.copilot
    - michelemelluso.gitignore
    - gitpod.gitpod-remote-ssh
    - dedsec727.jekyll-run
    - lonefy.vscode-js-css-html-formatter
    - mervin.markdown-formatter
    - esbenp.prettier-vscode
    - rebornix.ruby
    - mbessey.vscode-rufo
    - foxundermoon.shell-format
    - timonwong.shellcheck
    - hexcodetechnologies.vscode-prettydiff
    - redhat.vscode-yaml
    - neilding.language-liquid
    - wingrunr21.vscode-ruby
    - github.vscode-pull-request-githu

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
